### ISSUE TITLE
COSMIC Files issues

### ISSUE THREAD

**Issue by ImSabetDariush** [pop-os/cosmic-epoch#1010]
![screenshot-2024-09-26-10-15-27](https://github.com/user-attachments/assets/4210a49e-036a-4128-8ab7-c4bdea174aa2)
One of the problems I encountered recently in Cosmic File is that the details panel opens automatically.
Every time I click on a photo, this panel opens and it is very annoying, and it is better not to open this panel automatically and also to have the ability to change the size. When the window is small, the details panel takes up a lot of space.

![screenshot-2024-09-26-10-24-34](https://github.com/user-attachments/assets/d28796a9-023e-4ba0-a066-5f750c483795)
![screenshot-2024-09-26-10-24-23](https://github.com/user-attachments/assets/07d94a6e-03d3-4428-8ae5-87b12c992bbe)
Another problem is the user interface in compact mode.
In compact mode, the left panel is very close to the window, but the right panel is more distant. The left panel should have a little more space.

**Comment by WatchMkr** [comment]
The panel opening automatically is temporary until the "Show previews" option is added. We're experimenting with this feature at the moment.

Compact mode was enabled to identify spacing errors. We'll track this issue in the libcosmic repo because it applies to all apps: https://github.com/pop-os/libcosmic/issues/619
