### ISSUE TITLE
Flatpak app icons do not show up in cosmic-launcher or cosmic-app-list

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-epoch#107]
Most? running Flatpak icons do not appear. Slack, Mattermost, and Google Chrome (electron apps?) icons don't appear when running but Text Editor does. Todoist flatpak also shows up.

**Comment by tonyfarson** [comment]
### 🔍 Finding: COSMIC icon cache issue affects both Chrome PWAs *and* Flatpak apps

While investigating missing / placeholder (“gear”) icons for **Chrome PWAs** on **Pop!_OS 24.04 with COSMIC**, I discovered the same root cause also affects **Flatpak-installed applications**.

---

### ✅ What’s actually happening

- Both **Chrome (apt & Flatpak)** and **Flatpak apps** correctly:
  - Create `.desktop` files under  
    `~/.local/share/applications/`
  - Install icon PNGs under  
    `~/.local/share/icons/hicolor/<size>/apps/`
- The `.desktop` files reference valid icon names
- **Despite this**, COSMIC shows a generic placeholder icon

So the issue is **not missing icons** and **not malformed desktop files**.

---

### 🧠 Root cause (observed)
COSMIC does not appear to automatically rebuild or refresh the **user GTK icon cache** when new icons are added to the local `hicolor` theme.

As a result, icon lookups fail until the cache is manually rebuilt.

---

### 🛠️ Workaround / Fix

Running the following command immediately resolves the issue:

```bash
gtk-update-icon-cache -f -t ~/.local/share/icons/hicolor
