### ISSUE TITLE
Black screen when running on VM

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-epoch#110]
I tried to build this in a VM, using QEMU/KVM with virt-manager.
I notice there was 3 libs that was missing from the read-me:
- `cargo`
- `libgbm-dev`
- `libclang-dev`
- `libpipewire-0.3-dev`

I was using PopOS 22.04.
Also, `sudo apt install cosmic-*` doesn't worked somehow.

So after having successfully build the project, I made 
- `sudo cp -R ./cosmic-sysext /var/lib/extensions`
- `sudo systemctl enable --now systemd-sysext`
- `sudo systemd-sysext refresh`

Then after re login or reboot, when I choose Cosmic and enter the password, there is a black screen :(

I can type word like in a shell, but I can't type command. If I make ctrl-c, I go back to login.

**Comment by Drakulix** [comment]
VM support isn't great at the moment (e.g. see a similar issue for virtualbox here https://github.com/pop-os/cosmic-comp/issues/38).
You need to emulate a gpu with sufficient acceleration capabilities right now.

**Comment by wiiznokes** [comment]
I managed to make it work with virtualbox :)

Would a pull request with the libraries I listed and the `cp` command would be useful ?

**Comment by Drakulix** [comment]
The `cp`-command and the rest of the shell commands not so much. I want people to read about systemd-sysext and the caveats instead of blindly following instructions, to understand that this is not meant as a permanent installation and mostly for testing of pre-alpha software.

The missing libraries however I would appreciate very much. Thanks for documenting those.

**Comment by wiiznokes** [comment]
Done :)
