### ISSUE TITLE
Can't use the Space key in keyboard shortcuts

### ISSUE THREAD

**Issue by martinhiriart** [pop-os/cosmic-epoch#1142]
If I try to use the `Space`  key as part of a keyboard shortcut, the shortcut doesn't get saved at all.

For example, I tried copying the macOS spotlight keyboard shortcut of `CMD+Space` with its equivalent Windows keyboard alternative: `Alt+Space`, but could not get the settings to save.

I also confirmed that the Space key in particular is what is preventing the saving/modification of the keyboard shortcuts by trying other keys. For example, I created a custom keyboard shortcut to launch firefox (just an obvious visual indicator that the shortcut worked) with `Alt+F` and the setting saved and worked properly. If I tried to modify that to `Alt+Space` or any other keybind including the Space key, the changes never save.

**Comment by git-f0x** [comment]
I think lowercase `space` should be used, e.g. `Alt+space`.

**Comment by leviport** [comment]
As mentioned, this is pretty case-sensitive. Also, [a nicer way](https://github.com/pop-os/cosmic-settings/issues/499) to assign shortcuts is in the works, so the case sensitivity issue won't be an issue for much longer.

Since https://github.com/pop-os/cosmic-settings/issues/499 will fix shortcut assigning once implemented, I'm going to close this issue and we can track progress in https://github.com/pop-os/cosmic-settings/issues/499.

**Comment by martinhiriart** [comment]
Gotcha. Wasn't sure since some of the other key names were capitalized, but thanks for the update, I'll test it out shortly!
