### ISSUE TITLE
Idea: Automatic disk unlocking using TPM or Yubikey

### ISSUE THREAD

**Issue by TheCzechTayen** [pop-os/cosmic-epoch#1376]
**Hello there**,
my idea is that if the user chooses to encrypt the disk during installation, they will also be given the option of how to unlock it. For example, using a Yubikey hardware key or using a TPM chip, so that the whole decryption process could be automatic, or faster and more pleasant than typing a password nonstop.

What do u think?

**Comment by opreo** [comment]
from my understanding, this is theoretically possible but could be quite the undertaking.

i don't think i know of another Linux distro to have implemented this, and i feel like this would be a conversation better suited to a place concerning / about a distro rather than COSMIC (the desktop environment).

i believe the way bitlocker does it is indeed by leveraging the key when it is released by the TPM module, but yeah, i don't think it's a discussion for here lol

if your suggestion is more aimed at the Pop!_OS distro as a whole, maybe you could take it to https://github.com/pop-os/pop or somewhere else?

**Comment by TheCzechTayen** [comment]
Oh right, I keep forgetting that cosmic is just an environment and not a distro, my bad

**Comment by Drakulix** [comment]
Not applicable to cosmic, as already pointed out.
