### ISSUE TITLE
[Question] Would it be possible for the community to implement a custom "window manager"?

### ISSUE THREAD

**Issue by billksun** [pop-os/cosmic-epoch#151]
I love the design of the new rust-based COSMIC DE, and I am also very fond of the "scrollable tiling window manager" concept first brought to life by [PaperWM](https://github.com/paperwm/PaperWM) on Gnome, then [Cardboard](https://github.com/cardboardwm/cardboard) on Wayland via `wlroots` (no longer active), and now [Niri](https://github.com/YaLTeR/niri) on Wayland via `smithay`.

Having a scrollable tiling window manager in COSMIC DE is particularly appealing because it brings that experience to a batteries-included environment built on a rock-solid and performant foundation, and thus making it more accessible.

Is the current design modular enough to allow the community to build third-party window managers for COSMIC?

**Comment by jackpot51** [comment]
I don't think there'd be any problem with running the cosmic panel, applets, and applications on another wayland compositor.

**Comment by Drakulix** [comment]
> Is the current design modular enough to allow the community to build third-party window managers for COSMIC?

Yes absolutely. I cannot guarantee that this will work right now, but the goal is, that you could take `cosmic-session` and replace `cosmic-comp` with `sway` or `niri` and *most* things would still work.

Of course some functionality builds on custom-protocols used for the cosmic-environment (though we actively try to upstream and use upstream protocols where possible). But the goal is to have these applets deactivate certain functionalities and fail or fallback gracefully, so that most of the DE would still work as expected.

**Comment by billksun** [comment]
Thank you @jackpot51 and @Drakulix! This is really encouraging! Now I am even more excited about the new COSMIC DE and what I can do with it!
