### ISSUE TITLE
How to build deb packages

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-epoch#173]
I don't know much about the deb build process. Can you please tell me what commands need to be run, or where are located these commands if there are public.

Thank you

**Comment by jacobgkau** [comment]
You can build a deb package by `cd`'ing into the git repo of a submodule (e.g. `cosmic-comp` or `cosmic-applets`) and then running `dpkg-buildpackage -b -uc -us`. The package will be placed in the parent folder.

You can find the full explanation of `dpkg-buildpackage`'s options in its man page: https://man7.org/linux/man-pages/man1/dpkg-buildpackage.1.html 

I'm going to close this issue since it doesn't have anything to do with COSMIC, but feel free to leave another comment or stop by the [Mattermost chat server](https://chat.pop-os.org/) if you need more help.
