### ISSUE TITLE
Implement Super + Drag window shortcut

### ISSUE THREAD

**Issue by SUPERCILEX** [pop-os/cosmic-epoch#197]
This one is super useful. Hold super/meta and then click and drag a window around. It means you don't have to find the title bar to move a window.

**Comment by RillonDodgers** [comment]
Today I updated all my `comsic-*` packages and I'm able to Super + Drag now. Resizing does not work, both left click and right click + super lets me drag the window. I'll take it!

**Comment by jacobgkau** [comment]
Duplicate in the relevant repo: https://github.com/pop-os/cosmic-comp/issues/384 
Fixed by: https://github.com/pop-os/cosmic-comp/pull/389 

Thank you for the comments! Feel free to open a separate issue regarding any other shortcuts (keeping in mind the UX team and engineering will still need to approve of them first).

**Comment by XandrCopyrighted** [comment]
https://files.catbox.moe/7u5kem.mp4

**Comment by XandrCopyrighted** [comment]
> [files.catbox.moe/7u5kem.mp4](https://files.catbox.moe/7u5kem.mp4)

https://github.com/pop-os/cosmic-comp/issues/430#issuecomment-2064791117
