### ISSUE TITLE
Launcher + workspace switching behavior

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-epoch#203]
Currently, I can switch workspaces with Super + Ctrl + Up/Down while the Launcher is open. This also moves the selection cursor/highlight box up or down in the launcher, just like it does when Super + Ctrl aren't being held, and I'm just arrowing up and down through the items in the launcher. This feels like incorrect behavior, but I'm not exactly sure what the expected behavior should be.

In Gnome Cosmic, the launcher being open prevents workspace switching, and Super + Ctrl + Up/Down just does nothing. It would also seem reasonable to me to switch workspaces, but close the launcher while switching. 

(Opened in cosmic-epoch because I'm not exactly sure where it belongs. Feel free to transfer if there's a better repo for it)

**Comment by kauanfontanela** [comment]
> This also moves the selection cursor/highlight box up or down in the launcher

I dont get this behavior in `1.0.0.alpha.2.r0.g5c9757b-1` `AUR`. And I actually find quite useful that you can switch workspaces while the launcher is open.

For example: you open the launcher, type whatever app you want to open and only then realize "oh, this workspace is too crowded" instead of closing the launcher, reopening and typing all over again, you can just switch to the next workspace and open it
