### ISSUE TITLE
Is it too early to report some bugs?

### ISSUE THREAD

**Issue by garcia-s** [pop-os/cosmic-epoch#240]
Hello, I would like to know if I can report some bugs that I've found while using the cosmic DE as my main DE for a couple of days. However It might be too early and I just don't know if this is the right time. I'm by no means hurrying anybody up by reporting them. You guys probably have alot on your hands right now. I just want to help and let you know of anything I find. I would like to contribute in any way I can but I'm not good enough in rust just yet.

If it's not the right time, that's completely understandable.

EDIT: Also I'm not completely sure they are bugs either. They might be some features that are not yet available. So I do understand if I cannot report them, since the DE is on it's early state.

**Comment by cybin** [comment]
Well, as stated in the readme...

A call for testing will be announced when the project is ready for reports. 

Unfortunately, it's not that prominent and can be found under Installing on POP OS... :)

**Comment by garcia-s** [comment]
Oh ok, Thank you for your time. I missed that piece of information. I don't know how but I missed it. I'll make sure to have all the information I can collect about bugs (if I can find any by then). The project is awesome by the way. So I want to contribute as much as it's possible for me.

**Comment by jacobgkau** [comment]
While development is still ongoing, this project is being developed in an open-source manner, and you are welcome to report bugs now. It's best if you are able to write thorough bug reports and try to get them into the proper repository for what you're reporting. Also, please search through the existing issues before reporting a bug to ensure it's not already reported or hasn't been previously discussed.

You are also welcome to discuss things prior to opening bug reports in the ~cosmic-epoch channel of our Mattermost chat server (although we can't always reply to every single message in that server): https://chat.pop-os.org 

The alpha is going to be when we're comfortable telling semi-normal users they can give the environment an early look. I wouldn't expect it to significantly impact how we're handling bug reports, although it might to some extent since developer focus will sort of be transitioning from new feature development to polishing existing features around that time.
