### ISSUE TITLE
OSDs

### ISSUE THREAD

**Issue by ids1024** [pop-os/cosmic-epoch#30]
We'll need some layer-shell process providing OSDs for volume changes, screen brightness, alt-tab switching, etc.

**Comment by jokeyrhyme** [comment]
You could lean on the notifications daemon in #11 to provide volume and brightness feedback, by encoding the volume/brightness level in a notification "hint": https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html#hints

This is how `wired` users display such events as notifications: https://github.com/Toqozz/wired-notify/wiki/ProgressBlock#sending-progress-data

**Comment by WatchMkr** [comment]
Keyboard backlight and airplane mode

**Comment by WatchMkr** [comment]
Airplane Mode On/Off
Touchpad On/Off
Volume Up/Down
Mute On/Off
Display brightness up/down
Keyboard brightness up/down

**Comment by Bahasnyldz** [comment]
I don't think these OSDs should be the default but It would be nice if we could easily turn it on in the settings without needing a extension.
CapsLk On/Off
FnLock On/Off
NumLock On/Off

**Comment by leviport** [comment]
I wonder if an applet wouldn't be better for caps/numlock, similar to the Gnome extension. I have a hunch that users more frequently want to reference the current state of those locks, rather than be alerted when they change state. 

FnLock, however, is usually something that's handled in a laptop's embedded controller. This means it'll be very hardware-specific, and that's if the machine even attempts to communicate its state to the OS in the first place. Most I've seen just handle it in EC, independent of the OS entirely.

**Comment by boredsquirrel** [comment]
I would like to add that OSDs should be hidden if the settings popup is shown.

For example when opening the battery quicksettings and changing the brightness, there already is a slider shown.

Ideas:
- show the OSD only when the change is done via keyboard (if a feature to scroll over the battery icon was added like in KDE, this should trigger the OSD too)
- NOT show the OSD when the popup is shown

**Comment by leb-kuchen** [comment]
https://wiki.linuxquestions.org/wiki/XF86_keyboard_symbols
cosmic-comp#405 , if you want to design those

**Comment by gantryyork** [comment]
Can we make some of these applets, like sound volume, work by simply mousing over the applet and using the scroll wheel?
