### ISSUE TITLE
A "ghost window" appears when using Neovim with system clipboard.

### ISSUE THREAD

**Issue by theshatterstone** [pop-os/cosmic-epoch#344]
## Conditions to replicate:

* This bug happens when COSMIC is in tiling mode 

* Only in COSMIC (no such issues (or anything similar) in Hyprland, Qtile, or other Xorg or Wayland environments)

* In any terminal (tested kitty and COSMIC Terminal)

* In Neovim (but not regular vim)

* And only when neovim uses the system clipboard (set via ```vim.cmd("set clipboard=unnamedplus")``` in init.lua, for example)

* This bug does NOT happen with regular vim (regardless of clipboard usage), or vi mode in the shell, so it seems to be exclusive to Neovim.

* The bug only seems to affect tiling mode.

## Description:

When using any clipboard-related neovim command under these conditions, (commands tested include delete and yank commands), during the second keypress ("w" in "dw" or the second "y" in "yy"), the opened windows move, as if an invisible ghost window has opened and immediately closed right after a command like this is used. Sometimes, the appearance and disappearance of the invisible ghost window lasts as much as a second, triggering animations, and other times it's so fast it looks like the window flickered. 

## Other Relevant Information:
Distro: Fedora 40 Sway
Display/Login Manager: SDDM
CPU & GPU: AMD
Method of Installing COSMIC: COPR Repo (by ryanabx)

Also, I'm sorry if I missed any Issue Submission Guidelines, I looked around and couldn't find them.
If you have any questions or need more information, let me know.

What you're doing is amazing, Keep it Up!

**Comment by Drakulix** [comment]
Neovim is using wl-clipboard, which spawns a window get focus and access the keyboard (because you can't get clipboard access via wayland without focus. This is obviously a hack and completely unsupported by cosmic / unintended by the wayland protocol and will stop working once cosmic properly prevents focus-stealing.

There is unfortunately no good solution, the reason this works on e.g. wlroots based compositors, is that they implement the wlr_data_control protocol, which essentially gives full clipboard access to all application that want it, which is a privacy/security issue.

If you want this though, you can enable it by adding `data_control_enabled: true` to `/etc/cosmic-comp/config.ron`. It is not enabled by default.

A proper fix for this would require some integration between the terminal emulator (which has a window and thus normal clipboard access) and neovim, but as far as I know no such extension exists.

So yeah, this is (not) working as intended.

**Comment by theshatterstone** [comment]
Adding ```data_control_enabled: true``` to ```config.ron``` was the fix for it! Thank you! (Also, COSMIC is amazing! I'm only waiting for sloppy focus and static workspaces, and I'm switching to it full time!)

**Comment by roberte777** [comment]
> Neovim is using wl-clipboard, which spawns a window get focus and access the clipboard (because you can't get clipboard access via wayland without focus. This is obviously a hack and completely unsupported by cosmic / unintended by the wayland protocol and will stop working once cosmic properly prevents focus-stealing.
> 
> 
> 
> There is unfortunately no good solution, the reason this works on e.g. wlroots based compositors, is that they implement the wlr_data_control protocol, which essentially gives full clipboard access to all application that want it, which is a privacy/security issue.
> 
> 
> 
> If you want this though, you can enable it by adding `data_control_enabled: true` to `/etc/cosmic-comp/config.ron`. It is not enabled by default.
> 
> 
> 
> A proper fix for this would require some integration between the terminal emulator (which has a window and thus normal clipboard access) and neovim, but as far as I know no such extension exists.
> 
> 
> 
> So yeah, this is (not) working as intended.

I am experiencing this as well and just found this thread. Will this fix still work? I know keymaps used to be defined in this file but they no longer work (I don't think) as keymaps have been funny added to cosmic settings. So will this option still take effect? Or has the config.ron been completely replaced?
