### ISSUE TITLE
Fix Text Inconsistencies

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-epoch#354]
Typical applet
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/339cde21-3da1-4783-8ae1-25d51e0c7a6d)

App Tray text is larger
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/9df7d918-e247-4013-8b1c-9bf374119935)

Notifications tray text is larger
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/1d6db206-793b-4e8d-a217-7f3d872b286e)

App library and Launcher context menus are larger
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/2835b778-b231-4843-81d3-106754af2d47)
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/5d520893-4e60-4114-8607-26fb7c95eb88)

App Tray multiple windows text is small
![image](https://github.com/pop-os/cosmic-epoch/assets/3430283/2b46428d-ebf1-49a1-936b-91cb18fcd12c)

**Comment by maria-komarova** [comment]
I created a couple more issues to break it down into small steps:
- [ ] #375 
- [ ] #376 
- [ ] Adjust text size for window names under the window thumbnails (displayed when there are multiple windows of the same app running) to Body instead of Caption (adjusted in the [design](https://www.figma.com/design/4USmAaMoDyYYPzfxlhXV0M/Dock-%26-Top-Panel?node-id=5400-9728&t=2QbAfVkZzeU2ROPQ-4). 
- [ ] Adjust text size to Body inside the menu for launching on a specific GPU in the launcher.

**Comment by WatchMkr** [comment]
The last two now have issues on their repo:

https://github.com/pop-os/cosmic-applets/issues/481
https://github.com/pop-os/cosmic-launcher/issues/140

Closing and tracking with the issue in each repo.
