### ISSUE TITLE
New Stacks Designs

### ISSUE THREAD

**Issue by isaac-8601** [pop-os/cosmic-epoch#39]
This issue is a design proposal to update the visual style of our stacks (what we've called our tabbed windows in Pop!_OS), and to update some behaviors and add new functionality. Users should be able to move both tabs of a stack, and also the entire stack itself, with both the keyboard and the mouse. 

When changing the focus from one particular tab to a window outside the stack using the keyboard, there are many cases in which the focus of the stack will be on a tab the user does not want active. We're proposing a new behavior for changing focus from inside to outside a stack, detailed later in this issue.

We also want to improve the visual clarity of tabs and make it clearer which apps are currently in the stack.

## Designs

To improve clarity of the stacks, tabs will now have application icons, and the stack header itself will have a stack icon on the left. Users can use the spaces left and right of the tabs to drag the stack with their mouse. Behavior while dragging should match that of other windows indicated in [this issue](https://github.com/pop-os/cosmic-epoch/issues/35). Moving an entire stack with the keyboard will also be possible after using the [Select Outward keyboard shortcut](https://github.com/pop-os/cosmic-epoch/issues/38) and behavior should match other windows with our [new keyboard shortcut and tiling](https://github.com/pop-os/cosmic-epoch/issues/36).

![stack-header](https://user-images.githubusercontent.com/106764128/181650551-9cc3e711-be75-4cb0-94c7-09660ac22a6f.png)

When a user has several tabs and/or the length of the title exceeds the tab width, the title will go past the visible edge and a slight gradient will come over the title from the right side.

![stack-header-many-tabs](https://user-images.githubusercontent.com/106764128/181650594-873a39ef-2e79-4e1b-ae28-dc8ea4f13c7d.png)

We also propose new behavior for what happens when you hold down the Super key while moving focus outside of the stack. In the current system, focus remains on the most-recently focused tab, even if the user intended to change the active window _without_ changing which tab was active in the stack. Our proposal is that the behavior of releasing the Super key inside a stack will be unchanged; initiating window focus change inside a stack but releasing the Super key _outside_ of a stack will change window focus to the new window, but the stack will present the tab that was active when the Super key was first pressed. 

Single items can still move in and out of stacks, similar to current behavior. One change we will implement is animation in which tabs appear in the stack and move through the stack header along with the arrow keys.

![stack-1](https://user-images.githubusercontent.com/106764128/181652744-e4b04450-7bb0-430a-81a3-a1d439665931.gif)

**Comment by cloudFz** [comment]
I hope there will be an option to move the tabs to the bottom of a window. I prefer a taskbar to a dock so if the tabs are at the bottom it'll be like a taskbar.

**Comment by maria-komarova** [comment]
It's an interesting suggestion, we'll definitely consider it. It would also be helpful to learn how many people would like that option.

**Comment by maria-komarova** [comment]
We've been reviewing window stack headers because of some other questions but we realized there were a few things missing from the designs. So we've adjusted the designs for the window tabs and stack headers to account for it. 
- Window tabs now include the Close button and therefore app icon and window title are left-aligned inside the tab and close button is right aligned.
- Window tabs now have more states to make sure one can differentiate between selected tabs inside the active window stack and an inactive one. 
![Two-stacks-light](https://github.com/pop-os/cosmic-epoch/assets/57502897/dc34ce7b-2e37-4623-b172-24517f8b681a)
![Two-stacks-dark-1](https://github.com/pop-os/cosmic-epoch/assets/57502897/fcba8aa1-04a7-43cd-baed-7c3175f3c7f9)


- We've adjusted the colors to better align with the current state of COSMIC design system. 
- Tab overflow behavior was revisited and better outlined in the detailed prototype:
![window-tab-overflow](https://github.com/pop-os/cosmic-epoch/assets/57502897/c915ba69-f7fc-48c5-b49d-8f8fcfb4a841)

**Comment by Solarunit** [comment]
I like this idea, I remember MS was planning to add similar feature to Windows for years..
But I would rather like to have a real Task List on the Panel at the bottom. I am not a docker user at all.

Some ideas about stacked tabs:

- small (initial) tabs, do not expand them to the whole window size
- option to close tab by middle click
- option to hide close `x` button (to avoid accidental tabs closing)
