### ISSUE TITLE
Discord and Steam only receive mouse inputs below the bottom third of monitor

### ISSUE THREAD

**Issue by EpyonProjects** [pop-os/cosmic-epoch#391]
~~No other applications has this issue, it's just Discord.~~
Steam also has this issue

https://github.com/pop-os/cosmic-epoch/assets/66185010/605fac3e-4804-4484-814b-e9c8f95bacca

I had an issue prior with Discord's content (minus title bar) disappearing when scrolling, but was told to get popdev:master, which fixed that.

Hardware:
OS: Pop!_OS 22.04
CPU: Intel i7-12700K
GPU: MSI RTX 3080 12G
GPU driver: popdev:nvidia-555
Ram: 32 GB
Motherboard(?): ASUS TUF Gaming Z690-PLUS WIFI

**Comment by wiiznokes** [comment]
probably the same of https://github.com/pop-os/cosmic-comp/issues/397

**Comment by Drakulix** [comment]
You're output is at a negative position, I am pretty sure Xwayland doesn't support that.

Given the coordinate is -1080 on the y-axis and your resolution has 1440 pixels, that matches roughtly the lower third of the display.

We should sanitize positions in cosmic-comp to always start at (0, 0) and offset configurations automatically that extend into negative space. Thanks for the video, I am not sure I would've catched that detail otherwise!

**Comment by EpyonProjects** [comment]
https://github.com/pop-os/cosmic-epoch/assets/66185010/3de43fab-d806-45a9-b66f-608b12628ae1

Following up, this is the screen configuration, where I'm looking at my 1080p monitor and the displays are bottom aligned.  I was seeing an issue where I couldn't touch anything on Discord when they were top aligned, so the negative offset sounds accurate!

**Comment by EpyonProjects** [comment]
Closing this as I've not seen the issue since (though I may have moved my monitor placements since)
