### ISSUE TITLE
Multi screen doesn't work after disabling virtual screen.

### ISSUE THREAD

**Issue by osmancoskun** [pop-os/cosmic-epoch#538]
Hello Everyone.
First of all, congratulations with alpha release of the cosmic epoch.
I have tested cosmic epoch on Arch Linux.

here is my system configuration
```
OS: Arch Linux x86_64 
Host: MS-7C04 1.0 
Kernel: 6.10.3-arch1-2 
Shell: zsh 5.9 
Resolution: 2560x1440, 3840x2160 
CPU: Intel i9-9900 (16) @ 5.000GHz 
GPU: NVIDIA GeForce GTX 1060 6GB 
Memory: 3559MiB / 15924MiB 
```

After installing cosmic epoch, I saw there is a virtual display and i disabled that. then my mouse didn't move to other screen. It was on the right. I tried to move it around all corners and sides. Didn't work.

Hope there is some logs or configurations that I can share if you let me know

**Comment by Drakulix** [comment]
> After installing cosmic epoch, I saw there is a virtual display and i disabled that.

That is probably there because of your nvidia system, see https://github.com/pop-os/cosmic-comp/issues/641. Given you are on arch, you are not running our pop-os kernel, so the easiest way to fix this for you would probably be to add `nvidia-drm.fbdev=1` to your kernel command line.

> then my mouse didn't move to other screen. It was on the right. I tried to move it around all corners and sides. Didn't work.

Your displays are likely not touching each other in cosmic-settings. You need to re-layout them to be able to move the mouse between them.

**Comment by osmancoskun** [comment]
Thank you very much. Everything is working now. All i can say is, its amazingly fast and stable so far. Cant wait to see final product.
