### ISSUE TITLE
Discord, Slack or similar?

### ISSUE THREAD

**Issue by alshdavid** [pop-os/cosmic-epoch#565]
Hi all, any chance there is an official Discord, Slack, IRC or similar chat service for Cosmic? Had a look around and couldn't find anything. Thanks!

**Comment by jacobgkau** [comment]
The Pop!_OS Mattermost server is at https://chat.pop-os.org, and can be accessed via a web browser or the Mattermost desktop/mobile apps. The ~cosmic-epoch and ~development channels there would probably be what you're looking for.

We may switch to a different solution in the future since we're far over Mattermost's recommended user limits, but that's the place to go for now.

**Comment by exstntlmsnthrp** [comment]
If you do switch away from mattermost, PLEASE stick with something open source! Don't use discord or some other stupid steam-of-consciousness type of nonsense. It would be better to use GitHub discussions than something like that.

**Comment by jacobgkau** [comment]
GitHub Discussions is more of a forum and not really a replacement for a chat room. We're not considering Discord as an alternative. The only semi-serious consideration that's been floated so far is Matrix (we could still host our own server if we go that route, while still lowering the barrier to entry compared to the current Mattermost server).

**Comment by exstntlmsnthrp** [comment]
> GitHub Discussions is more of a forum and not really a replacement for a chat room.

Agreed, completely. 

Chat room style apps/services, regardless of open source or not, are just not effective ways to find help and solutions. 

Very pleased to hear about the commitment to open source! Thank you.
