### ISSUE TITLE
[BUG] Terminal running nvim resizing when in tiling mode

### ISSUE THREAD

**Issue by Ryan-Vreeke** [pop-os/cosmic-epoch#682]
**Issue Summary:**

When using Neovim in a terminal, performing certain actions like deleting a line with dd or copying a line with yy causes the following behavior:

   - **Tiling Mode**: The terminal window briefly flickers, shrinks to half its size, and then immediately resizes to fill its tile location.
   - **Floating Mode**: The window flickers but does not resize.
 
**System Spec**
OS: Garuda Linux
Terminal: cosmic-term
CPU: AMD Ryzen 9 5900HS with Radeon Graphics (16) @ 4.6
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q
GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobile Se

**Comment by andrei-pavel** [comment]
I just started using Cosmic DE and noticed immediately that this happens to me too with vim 9.1.

It only untiles for me. I see no flicker or intermediate resizing.

Apart from `dd` and `yy`, it also happens if you press `P` for pasting. Only in normal mode.

<details>
<pre><code>$ pacman -Qi xdg-desktop-portal-cosmic
Name            : xdg-desktop-portal-cosmic
Version         : 1.0.0.alpha.1-1
</code></pre>

<pre><code>$ fastfetch -l none



OS    ➜  EndeavourOS x86_64
 ├   ➜  Linux 6.10.10-arch1-1
 ├ 󰏖  ➜  2548 (pacman)
 └   ➜  zsh 5.9

WM    ➜  cosmic-comp (Wayland)
 ├ 󰀻  ➜  Papirus-Dark [GTK2/3]
 ├   ➜  Bibata-Modern-Ice (24px)
 ├   ➜  tilix
 └   ➜  Intel One Mono (10pt, Light)

 ├   ➜  AMD Ryzen 9 7950X (16) @ 5.88 GHz GHz
 ├ 󰢮  ➜  AMD AMD Radeon RX 6500 XT @  GHz
 ├ 󰢮  ➜  AMD Raphael @  GHz
 ├   ➜  9.56 GiB / 62.02 GiB (15%)
 ├ 󰓡  ➜  Disabled
 ├ 󰋊  ➜  792.18 GiB / 1.83 TiB (42%) - ext4
 └   ➜  3840x2160 px @ 59.981 Hz - 700x390 mm (31.55 inches, 139.66 ppi)
 └   ➜  3840x2160 px @ 59.981 Hz - 600x340 mm (27.15 inches, 162.27 ppi)
</code></pre>

<pre><code>$ vim --version
VIM - Vi IMproved 9.1 (2024 Jan 02, compiled Aug 31 2024 21:12:10)
Included patches: 1-707
Compiled by Arch Linux
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl/dyn
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      -sodium            -X11
+digraphs          +mouse             -sound             +xattr
-dnd               -mouseshape        +spell             -xfontset
-ebcdic            +mouse_dec         +startuptime       -xim
+emacs_tags        +mouse_gpm         +statusline        -xpm
+eval              -mouse_jsbterm     -sun_workshop      -xsmp
+ex_extra          +mouse_netterm     +syntax            -xterm_clipboard
+extra_search      +mouse_sgr         +tag_binary        -xterm_save
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
 3rd user vimrc file: "~/.config/vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/build/vim/src=/usr/src/debug/vim -flto=auto -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.38/core_perl/CORE -Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs -flto=auto -L/usr/local/lib -o vim -lm -ltinfo -lacl -lattr -lgpm -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm </code></pre></details>
