### ISSUE TITLE
[General discussion/fluff] daily driving cosmic

### ISSUE THREAD

**Issue by Department-stack** [pop-os/cosmic-epoch#720]
I have been using cosmic about a week before alpha on my fedora machine and it was 70 percent functional at the time but now that is more closer to 90 percent to me. This desktop environment is something I have been daily driving for about 2 weeks and besides the bug reports I've posted I haven't had any other issues. Its actually pretty great and this is only the alpha. Most of the issues I encounter I can adapt to so it really isn't a long term issue. I've always wanted to get into tiling but not use a sole tiling window manager. In some aspects I am more proficient than I would be in using KDE. But the same also applies the other way around. So overall it balances out. I doubt I'll fully ditch KDE but 95 percent of my time is now in cosmic. I'm excited for future releases and being apart of this community as a whole. 😊

**Comment by leviport** [comment]
Thank you very much for your feedback! If you wish to have general discussions about Pop and/or COSMIC DE, please stop by our Mattermost chat room: https://chat.pop-os.org/

Since we use Github issues to track development, we prefer for general discussion to happen in that chat, rather than our github issues.
