### ISSUE TITLE
Steps to install on regular Ubuntu

### ISSUE THREAD

**Issue by virtualritz** [pop-os/cosmic-epoch#80]
I'm on Ubuntu 22.04.
I am following the steps in the README:

```
sudo cp -R cosmic-sysext /var/lib/extensions
sudo systemctl enable --now systemd-sysext
sudo systemd-sysext refresh
```

I now have `cosmic` as an option in my display manager during login. But if I choose it, I get a black screen.

Is there anything missing from the steps in the README or anything I misunderstood?

**Comment by virtualritz** [comment]
I updated my nvidia driver and I now get the cosmic desktop. With a menu bar at the top with date & time. That's it.

How do I get the apps etc.? Is there a way to build the Debian packages e.g.?

**Comment by Drakulix** [comment]
> How do I get the apps etc.?

By default the desktop is lacking key-bindings, you need to copy [this config file](https://github.com/pop-os/cosmic-comp/blob/master_jammy/config.ron) to `/etc/cosmic-comp/config.run`.
Then you can use `Super + /` to bring up the launcher and `Super + a` to bring up the App Library.

> Is there a way to build the Debian packages e.g.?

You can build them like any other using `dpkg-buildpackage` in the respective repositories.

The instructions are by design distribution-agnostic for now. We expect proper packaging for different distributions to to happen once we release a first version and will gladly assist building them at that time.

**Comment by virtualritz** [comment]
When I have `systemd-sysext` running `/usr` becomes read only which leads to all kinds of breakage when trying to e.g. run `apt` to update stuff:

```
mount | rg usr  
sysext on /usr type overlay (ro,relatime,lowerdir=/run/systemd/sysext/meta/usr:/run/systemd/sysext/extensions/cosmic-sysext/usr:/usr)
```

I guess this is not meant to happen? What config steps are missing from the README in that regard?

**Comment by wiiznokes** [comment]
> I now have cosmic as an option in my display manager during login. But if I choose it, I get a black screen.

@virtualritz please, what driver did you use? And was wayland enabled? I have the same problem
