### ISSUE TITLE
RFC: Changing xdg-desktop-portal-cosmic's location from libexec to just lib

### ISSUE THREAD

**Issue by Vixea** [pop-os/cosmic-epoch#87]
/usr/libexec doesn't exist on arch and probably other distros it would increase compatibility to just store it in /usr/lib instead. What's the reason for putting it in libexec as someone who comes from a distro that doesn't use it?

**Comment by Drakulix** [comment]
Usually on distributions `/usr/lib` is meant for libraries, while `/usr/libexec` is meant for implementation-detail binaries, which are not included in `PATH` by design.
Using `/usr/lib` for that purpose like arch linux does, obviously also works (as `/usr/lib` is not in path), but is definitely less common.

For easier packaging we should make this configurable though. Which concerns the launch-path in `cosmic-session`, the build scripts of `xdg-desktop-portal-cosmic` and it's portal service file, which likely would need to be replaced by a template of sorts.

**Comment by soloturn** [comment]
@drakulix, the two biggest distributions, debian (+ ubuntu with it), and arch, never fell in love with libexec. it is more a red hat and bsd thingy. some discussion from 2005 here, where FHS did not even mention libexec: https://lists.debian.org/debian-devel/2005/05/msg00401.html. meanwhile FHS got extended though, and mention libexec as optional. 

as pop has debian/ubuntu on its base, it sounds a little weird that you use libexec :) as FHS just has it as optional, it needs, at least imo, not even be a config option.

**Comment by Drakulix** [comment]
There is a discussion to be had on changing the default. There even is a discussion to be had to change the current hard-coded location short term.

But hard-coding definitely is not the better solution. If different distributions simply have these binaries at different locations, we need to make that configurable long term. Period.

**Comment by soloturn** [comment]
here the 3 libexec paths @yochananmarqos corrected in the arch build:
* https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=cosmic-epoch-git#n94

**Comment by Vixea** [comment]
Just a little ping, would be nice to have with the alpha

**Comment by Vixea** [comment]
ok I see that you changed the just file I'm letting packagers on arch know I think this can be closed right. @soloturn

**Comment by Vixea** [comment]
I think this issue can be closed now that you can change it in the justfile

**Comment by Vixea** [comment]
Alright imma close it myself lol
