### ISSUE TITLE
Cosmic DE is just a blank grey screen with the number 1 on the top left. build yesterday

### ISSUE THREAD

**Issue by LethalManBoob** [pop-os/cosmic-epoch#90]
Is there something im missing? Im on Archlinux atm. Will provide any specifics if asked.

**Comment by LethalManBoob** [comment]
I tried the /etc/cosmic-comp/config.run thing but still, nothing works.

**Comment by Drakulix** [comment]
As you can see this repository and as such the referenced commits of it's subprojects have not been touched in the last two weeks. So I am not sure, how you would just now get such a broken setup.

Can you please provide some log files, specifically from:

- `journalctl --user _EXE=/usr/bin/cosmic-comp -e`
- and `journalctl --user _EXE=/usr/bin/cosmic-session -e`

That should help us figuring out whats wrong.

**Comment by LethalManBoob** [comment]
[cosmic-session.txt](https://github.com/pop-os/cosmic-epoch/files/11185828/cosmic-session.txt)
[cosmic-comp.txt](https://github.com/pop-os/cosmic-epoch/files/11185829/cosmic-comp.txt)

**Comment by Drakulix** [comment]
Looks mostly like a permission problem, how are you launching cosmic? Through a login manager? If so, which one?

**Comment by LethalManBoob** [comment]
Through GDM login.

**Comment by Drakulix** [comment]
Can you maybe upload a short video of the issue? The logs look suspiciously okay..

**Comment by LethalManBoob** [comment]
https://www.veed.io/view/cb8a23e2-fdbd-4805-9c9f-f9118876e6da?sharingWidget=true&panel=share

**Comment by Drakulix** [comment]
That looks just fine. Compositor and panel are both running.
So the question here is, what are expecting to be different?

**Comment by LethalManBoob** [comment]
Seeing some of the screenshots from various news sites I expected "some" degree of usability by now.

**Comment by Drakulix** [comment]
Well, then this issue was a bit misleading, at least to me. :sweat_smile: 

Anyway:

It is usable. If you have the default config for cosmic-comp installed for example:
  - You can open a launcher with `Super+/` to start apps and more.
  - You can open the application library with `Super+a`
  - You have applets in the top-bar like the "Number 1", being a workspace indicator, or audio, network, bluetooth, power applets.
  - There is a Dock showing active applications and allowing you to pin Favorites.
  - You can switch between workspace, control tiling and a lot more with shortcuts - as you can see in the default config.
  - If you have been using Pop!_OS many shortcuts should feel right at home.

> At a minimum I was expecting to be able to click around a few settings.

But that is the point, where I have to remind you, that this is a Pre-Alpha.
- While we do have a usable desktop, thing you might expect for a minimum value product (MVP) - like a settings app - are not there yet. Why you might ask?
- Well there are multiple reasons:
  - It is not required to actually test the other stuff...
  - ...because all tools have config files, you can edit.
  - Building a completely new toolkit is difficult and cosmic-settings will be the first normal app writting in our iced-toolkit.
  - And settings is also not exactly a super small application and also has to interface with a lot of subsystems, like configuring panels, the shell, applets, etc...
  - ... which is a lot easier, when said applets, panels, etc exist, which is why Settings is like the last component for our MVP to be ready.
  
> Seeing some of the screenshots from various news sites I expected "some" degree of usability by now.

A lot of what you are seeing is there and we are using it daily, but it is lacking documentation on how to get there.
For example the config file formats change frequently and are not really documented. People already running the desktop like dig through the code to figure out how to do things like setting a wallpaper. And while we are still building base functionality this will likely continuing being the case. Once the first alpha rolls out, we expect all key components to be in place for an intuitive experience, like - of course - a settings app. But right now we are still working on that.

**Comment by LethalManBoob** [comment]
That clears a lot up. I really figured I was doing something wrong. Alright. Yeah, Ill wait until the first alpha.
